import {
  User,
  Workspace,
  Project,
  Task,
  NotificationItem,
  ActivityLogItem,
  Label,
} from "@/types/taskflow";

export const currentUser: User = {
  id: "u-1",
  name: "Bilal Khan",
  email: "bilal@taskflow.dev",
  jobTitle: "Product Lead & Admin",
  avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80",
  timezone: "Asia/Karachi",
  role: "owner",
};

export const teamMembers: User[] = [
  currentUser,
  {
    id: "u-2",
    name: "Sara Ali",
    email: "sara@taskflow.dev",
    jobTitle: "Lead UI/UX Designer",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80",
    timezone: "Asia/Karachi",
    role: "manager",
  },
  {
    id: "u-3",
    name: "John Doe",
    email: "john@taskflow.dev",
    jobTitle: "Full-Stack Engineer",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80",
    timezone: "Europe/London",
    role: "member",
  },
  {
    id: "u-4",
    name: "Ayesha Noor",
    email: "ayesha@taskflow.dev",
    jobTitle: "QA & DevOps Lead",
    avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120&auto=format&fit=crop&q=80",
    timezone: "Asia/Karachi",
    role: "member",
  },
  {
    id: "u-5",
    name: "Hamza Tariq",
    email: "hamza@taskflow.dev",
    jobTitle: "Marketing Strategist",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80",
    timezone: "Asia/Karachi",
    role: "viewer",
  },
];

export const workspaces: Workspace[] = [
  {
    id: "ws-1",
    name: "Acme Corp Workspace",
    slug: "acme-corp",
    ownerId: "u-1",
    membersCount: 5,
    projectsCount: 4,
  },
  {
    id: "ws-2",
    name: "Personal Projects",
    slug: "personal-bilal",
    ownerId: "u-1",
    membersCount: 1,
    projectsCount: 2,
  },
];

export const labels: Label[] = [
  { id: "lbl-1", name: "Design", color: "#0F766E" },
  { id: "lbl-2", name: "Backend", color: "#2E7CD6" },
  { id: "lbl-3", name: "Security", color: "#C0342B" },
  { id: "lbl-4", name: "Bug", color: "#D97706" },
  { id: "lbl-5", name: "Feature", color: "#15803D" },
];

export const initialProjects: Project[] = [
  {
    id: "proj-1",
    workspaceId: "ws-1",
    name: "Website Redesign",
    description: "Revamp the marketing landing page and design system with high-speed Next.js 14 and Tailwind.",
    color: "#0F766E",
    icon: "globe",
    status: "active",
    startDate: "2026-08-15",
    deadline: "2026-09-20",
    progress: 68,
    totalTasks: 18,
    completedTasks: 12,
    members: [teamMembers[0], teamMembers[1], teamMembers[2]],
  },
  {
    id: "proj-2",
    workspaceId: "ws-1",
    name: "Recruitment Platform",
    description: "Applicant tracking system and candidate onboarding portal with automated interview scheduling.",
    color: "#2E7CD6",
    icon: "users",
    status: "active",
    startDate: "2026-08-01",
    deadline: "2026-09-30",
    progress: 42,
    totalTasks: 24,
    completedTasks: 10,
    members: [teamMembers[0], teamMembers[2], teamMembers[3]],
  },
  {
    id: "proj-3",
    workspaceId: "ws-1",
    name: "Mobile App iOS",
    description: "React Native client for iOS & Android task syncing and offline-first queue.",
    color: "#D97706",
    icon: "smartphone",
    status: "active",
    startDate: "2026-08-20",
    deadline: "2026-10-15",
    progress: 25,
    totalTasks: 16,
    completedTasks: 4,
    members: [teamMembers[0], teamMembers[1], teamMembers[4]],
  },
  {
    id: "proj-4",
    workspaceId: "ws-1",
    name: "Brand Marketing Campaign",
    description: "Q3 global launch assets, social media graphics, and customer interview digests.",
    color: "#6941C6",
    icon: "send",
    status: "planning",
    startDate: "2026-09-10",
    deadline: "2026-11-01",
    progress: 10,
    totalTasks: 8,
    completedTasks: 1,
    members: [teamMembers[0], teamMembers[4]],
  },
];

export const initialTasks: Task[] = [
  {
    id: "task-101",
    projectId: "proj-1",
    title: "Design clean paper layout tokens in Figma",
    description: "Establish strict 4px spacing scale, deep teal `#0F766E` brand action states, and neutral status tokens.",
    status: "done",
    priority: "high",
    assignee: teamMembers[1], // Sara Ali
    watchers: [teamMembers[0]],
    startDate: "2026-08-16",
    dueDate: "2026-08-22",
    completedAt: "2026-08-22T14:30:00Z",
    estimatedHours: 12,
    actualHours: 10,
    position: 0,
    labels: [labels[0]],
    subtasks: [
      { id: "st-1", taskId: "task-101", title: "Setup color variables", isCompleted: true },
      { id: "st-2", taskId: "task-101", title: "Typography scales in Inter", isCompleted: true },
      { id: "st-3", taskId: "task-101", title: "Export SVG icons", isCompleted: true },
    ],
    attachments: [
      {
        id: "att-1",
        taskId: "task-101",
        fileName: "taskflow-design-system-v1.fig",
        fileUrl: "#",
        fileType: "application/figma",
        fileSize: 4200000,
        uploadedBy: teamMembers[1],
        createdAt: "2026-08-20T10:00:00Z",
      },
    ],
    comments: [
      {
        id: "c-1",
        taskId: "task-101",
        user: teamMembers[0],
        content: "Looks stunning! The contrast ratio on white surfaces is crisp.",
        createdAt: "2026-08-21T11:00:00Z",
      },
    ],
    createdAt: "2026-08-16T09:00:00Z",
    updatedAt: "2026-08-22T14:30:00Z",
  },
  {
    id: "task-102",
    projectId: "proj-1",
    title: "Implement dnd-kit Sortable Kanban board",
    description: "Support 5 columns (Backlog, To Do, In Progress, In Review, Done) with smooth drag transitions and keyboard navigation.",
    status: "in_progress",
    priority: "urgent",
    assignee: teamMembers[0], // Bilal Khan
    watchers: [teamMembers[1], teamMembers[2]],
    startDate: "2026-09-01",
    dueDate: "2026-09-08", // Today / Tomorrow
    estimatedHours: 16,
    actualHours: 8,
    position: 0,
    labels: [labels[0], labels[4]],
    subtasks: [
      { id: "st-4", taskId: "task-102", title: "PointerSensor distance constraint (5px)", isCompleted: true },
      { id: "st-5", taskId: "task-102", title: "Keyboard navigation accessibility", isCompleted: true },
      { id: "st-6", taskId: "task-102", title: "DragOverlay card preview with slight lift", isCompleted: true },
      { id: "st-7", taskId: "task-102", title: "Optimistic reordering update", isCompleted: false },
    ],
    attachments: [],
    comments: [
      {
        id: "c-2",
        taskId: "task-102",
        user: teamMembers[2],
        content: "@Bilal Khan make sure to verify cross-column drop targets on mobile view.",
        createdAt: "2026-09-05T16:20:00Z",
      },
    ],
    createdAt: "2026-09-01T08:00:00Z",
    updatedAt: "2026-09-06T10:15:00Z",
  },
  {
    id: "task-103",
    projectId: "proj-1",
    title: "Setup PostgreSQL schema & Prisma relations",
    description: "Write complete models for Users, Workspaces, Projects, Tasks, Subtasks, ActivityLog, and Comments.",
    status: "in_review",
    priority: "high",
    assignee: teamMembers[2], // John Doe
    watchers: [teamMembers[0]],
    startDate: "2026-09-02",
    dueDate: "2026-09-09",
    estimatedHours: 10,
    actualHours: 9,
    position: 0,
    labels: [labels[1]],
    subtasks: [
      { id: "st-8", taskId: "task-103", title: "Prisma schema with indexes", isCompleted: true },
      { id: "st-9", taskId: "task-103", title: "Zod validations for all payloads", isCompleted: true },
      { id: "st-10", taskId: "task-103", title: "Migration scripts", isCompleted: false },
    ],
    attachments: [
      {
        id: "att-2",
        taskId: "task-103",
        fileName: "schema-architecture.png",
        fileUrl: "#",
        fileType: "image/png",
        fileSize: 840000,
        uploadedBy: teamMembers[2],
        createdAt: "2026-09-04T12:00:00Z",
      },
    ],
    comments: [],
    createdAt: "2026-09-02T10:00:00Z",
    updatedAt: "2026-09-06T15:00:00Z",
  },
  {
    id: "task-104",
    projectId: "proj-2",
    title: "Implement candidate interview scheduling calendar",
    description: "Monthly calendar view with slot pickers and timezone safety for recruiters.",
    status: "todo",
    priority: "medium",
    assignee: teamMembers[3], // Ayesha Noor
    watchers: [teamMembers[0]],
    startDate: "2026-09-05",
    dueDate: "2026-09-12",
    estimatedHours: 14,
    actualHours: 0,
    position: 0,
    labels: [labels[4]],
    subtasks: [
      { id: "st-11", taskId: "task-104", title: "Monthly grid renderer", isCompleted: false },
      { id: "st-12", taskId: "task-104", title: "Timezone conversion helper (date-fns)", isCompleted: false },
    ],
    attachments: [],
    comments: [],
    createdAt: "2026-09-05T11:00:00Z",
    updatedAt: "2026-09-05T11:00:00Z",
  },
  {
    id: "task-105",
    projectId: "proj-2",
    title: "Audit security headers & rate limiting",
    description: "Configure Helmet.js, CORS allowlists, and 100 req/min rate limiters.",
    status: "backlog",
    priority: "high",
    assignee: teamMembers[3], // Ayesha Noor
    watchers: [teamMembers[0]],
    startDate: "2026-09-15",
    dueDate: "2026-09-25",
    estimatedHours: 8,
    actualHours: 0,
    position: 0,
    labels: [labels[2]],
    subtasks: [],
    attachments: [],
    comments: [],
    createdAt: "2026-09-06T09:30:00Z",
    updatedAt: "2026-09-06T09:30:00Z",
  },
  {
    id: "task-106",
    projectId: "proj-3",
    title: "Design mobile bottom tab navigation bar",
    description: "Compact navigation matching < 640px responsive specs in Section 11.8.",
    status: "todo",
    priority: "low",
    assignee: teamMembers[1], // Sara Ali
    watchers: [],
    startDate: "2026-09-08",
    dueDate: "2026-09-15",
    estimatedHours: 6,
    actualHours: 0,
    position: 1,
    labels: [labels[0]],
    subtasks: [],
    attachments: [],
    comments: [],
    createdAt: "2026-09-06T14:00:00Z",
    updatedAt: "2026-09-06T14:00:00Z",
  },
  {
    id: "task-107",
    projectId: "proj-1",
    title: "Fix authentication token refresh expiry bug",
    description: "Ensure silent refresh token rotation occurs 1 minute prior to 15m JWT expiration.",
    status: "in_progress",
    priority: "urgent",
    assignee: teamMembers[0], // Bilal Khan
    watchers: [teamMembers[2]],
    startDate: "2026-09-04",
    dueDate: "2026-09-07", // Overdue / Due Today
    estimatedHours: 5,
    actualHours: 3,
    position: 1,
    labels: [labels[2], labels[3]],
    subtasks: [
      { id: "st-13", taskId: "task-107", title: "Reproduce 401 unhandled rejection", isCompleted: true },
      { id: "st-14", taskId: "task-107", title: "Write interceptor retry loop", isCompleted: true },
      { id: "st-15", taskId: "task-107", title: "Unit test with mock clock", isCompleted: false },
    ],
    attachments: [],
    comments: [],
    createdAt: "2026-09-04T16:00:00Z",
    updatedAt: "2026-09-06T11:00:00Z",
  },
];

export const initialNotifications: NotificationItem[] = [
  {
    id: "notif-1",
    userId: "u-1",
    type: "assignment",
    title: "New Task Assigned",
    message: "Sara Ali assigned you to 'Implement dnd-kit Sortable Kanban board'.",
    linkUrl: "task-102",
    isRead: false,
    relatedTaskId: "task-102",
    createdAt: "2026-09-07T06:30:00Z",
  },
  {
    id: "notif-2",
    userId: "u-1",
    type: "mention",
    title: "Mentioned in Comment",
    message: "John Doe mentioned you in 'Implement dnd-kit Sortable Kanban board'.",
    linkUrl: "task-102",
    isRead: false,
    relatedTaskId: "task-102",
    createdAt: "2026-09-07T05:20:00Z",
  },
  {
    id: "notif-3",
    userId: "u-1",
    type: "due_soon",
    title: "Deadline Reminder",
    message: "'Fix authentication token refresh expiry bug' is due today at 18:00.",
    linkUrl: "task-107",
    isRead: false,
    relatedTaskId: "task-107",
    createdAt: "2026-09-07T02:00:00Z",
  },
  {
    id: "notif-4",
    userId: "u-1",
    type: "status_change",
    title: "Task Completed",
    message: "Sara Ali marked 'Design clean paper layout tokens in Figma' as Done.",
    linkUrl: "task-101",
    isRead: true,
    relatedTaskId: "task-101",
    createdAt: "2026-09-06T18:00:00Z",
  },
];

export const initialActivityLogs: ActivityLogItem[] = [
  {
    id: "act-1",
    user: teamMembers[1], // Sara Ali
    action: "status_changed",
    details: "moved 'Design clean paper layout tokens' from In Review to Done",
    projectName: "Website Redesign",
    createdAt: "2 hours ago",
  },
  {
    id: "act-2",
    user: teamMembers[2], // John Doe
    action: "commented",
    details: "commented on 'Implement dnd-kit Sortable Kanban board'",
    projectName: "Website Redesign",
    createdAt: "3 hours ago",
  },
  {
    id: "act-3",
    user: teamMembers[0], // Bilal Khan
    action: "assigned",
    details: "assigned 'Audit security headers' to Ayesha Noor",
    projectName: "Recruitment Platform",
    createdAt: "5 hours ago",
  },
  {
    id: "act-4",
    user: teamMembers[0], // Bilal Khan
    action: "created",
    details: "created new project 'Mobile App iOS'",
    projectName: "Mobile App iOS",
    createdAt: "1 day ago",
  },
  {
    id: "act-5",
    user: teamMembers[1], // Sara Ali
    action: "file_uploaded",
    details: "uploaded attachment 'taskflow-design-system-v1.fig'",
    projectName: "Website Redesign",
    createdAt: "1 day ago",
  },
];
